firebase.initializeApp(firebaseConfig);
const auth=firebase.auth(),db=firebase.firestore(),$=s=>document.querySelector(s);
let user=null,custom=[],versionsCache=[],unsubscribeVersions=null;
const read=()=>Object.fromEntries([...document.querySelectorAll('[data-key]')].map(i=>[i.dataset.key,i.value]));
const write=d=>document.querySelectorAll('[data-key]').forEach(i=>i.value=d?.[i.dataset.key]||'');
function refresh(){if(unsubscribeVersions)unsubscribeVersions();unsubscribeVersions=db.collection('simulationVersions').orderBy('number','desc').onSnapshot(snap=>{versionsCache=snap.docs.map(d=>({id:d.id,...d.data()}));render()},e=>alert('Firestore 실시간 연결에 실패했습니다: '+e.message))}
function render(){const rows=versionsCache;$('#history').innerHTML=rows.length?rows.map(v=>`<div class="history-row"><strong>v${v.number}</strong><div><div>${v.name||'이름 없는 시뮬레이션'}</div><small>${new Date(v.savedAt).toLocaleString('ko-KR')}</small></div><div><button data-load="${v.id}">불러오기</button><button class="danger" data-delete="${v.id}">삭제</button></div></div>`).join(''):'<div class="empty">저장된 버전이 없습니다.</div>';$('#history').querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>load(b.dataset.load));$('#history').querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>del(b.dataset.delete))}
function renderCustom(){document.querySelectorAll('[data-custom="true"]').forEach(n=>n.remove());custom.forEach(f=>$('.orders .fields').insertAdjacentHTML('beforeend',`<div class="field" data-custom="true"><label>${f.label}</label><input data-key="${f.key}" placeholder="입력하세요"></div>`))}
async function save(){const n=versionsCache.length?Math.max(...versionsCache.map(v=>v.number))+1:1;await db.collection('simulationVersions').add({number:n,name:$('#name').value.trim()||`시뮬레이션 v${n}`,savedAt:new Date().toISOString(),data:read(),custom,createdBy:user.uid});$('#versionLabel').textContent=`v${n} 저장됨`}
function load(id){const v=versionsCache.find(x=>x.id===id);if(!v)return;custom=v.custom||[];renderCustom();write(v.data);$('#name').value=v.name;$('#versionLabel').textContent=`v${v.number} 불러옴`}
async function del(id){if(!confirm('이 버전을 삭제할까요?'))return;await db.collection('simulationVersions').doc(id).delete()}
$('#settingsBtn').onclick=()=>{manager();$('#settingsDialog').showModal()};$('#addField').onclick=()=>{const label=$('#addLabel').value.trim();if(!label)return;custom.push({key:'custom_'+Date.now(),label});$('#addLabel').value='';renderCustom();manager()};$('#saveBtn').onclick=save;$('#newBtn').onclick=()=>{custom=[];renderCustom();write();$('#name').value='';$('#versionLabel').textContent='새 시뮬레이션'};
function manager(){const box=$('#fieldManager');box.innerHTML='';custom.forEach(f=>box.insertAdjacentHTML('beforeend',`<div class="manager-row"><span>${f.label} · 추가 항목</span><button type="button" class="danger" data-remove-custom="${f.key}">삭제</button></div>`));box.querySelectorAll('[data-remove-custom]').forEach(b=>b.onclick=()=>{custom=custom.filter(f=>f.key!==b.dataset.removeCustom);renderCustom();manager()})}
auth.setPersistence(firebase.auth.Auth.Persistence.LOCAL);
const googleProvider=new firebase.auth.GoogleAuthProvider();
async function showApp(u){user=u;$('#loginScreen').hidden=true;$('#loginScreen').style.display='none';$('#appScreen').hidden=false;$('#appScreen').style.display='block';$('#authStatus').textContent=u.email||u.displayName||'로그인 사용자';renderCustom();refresh()}
$('#loginBtn').onclick=async()=>{try{const result=location.hostname==='localhost'||location.hostname==='127.0.0.1'?await auth.signInWithRedirect(googleProvider):await auth.signInWithPopup(googleProvider);if(result?.user)await showApp(result.user)}catch(e){alert('Google 로그인에 실패했습니다: '+e.message)}};
$('#logoutBtn').onclick=()=>auth.signOut();
auth.getRedirectResult().then(result=>{if(result.user)user=result.user}).catch(e=>{console.error(e);const message=e.code==='auth/operation-not-allowed'?'Firebase 콘솔에서 Google 로그인을 활성화해주세요.':'Google 로그인에 실패했습니다: '+e.message;alert(message)});
auth.onAuthStateChanged(async u=>{if(u)await showApp(u);else{$('#loginScreen').hidden=false;$('#loginScreen').style.display='';$('#appScreen').hidden=true;$('#appScreen').style.display='none';$('#history').innerHTML='';}});

function manager(){const box=$('#fieldManager');box.innerHTML='';document.querySelectorAll('.field[data-field-id]').forEach(row=>box.insertAdjacentHTML('beforeend',`<div class="manager-row"><span>${row.querySelector('label').textContent} · 기본 항목</span><button type="button" class="danger" data-remove-fixed="${row.dataset.fieldId}">삭제</button></div>`));custom.forEach(f=>box.insertAdjacentHTML('beforeend',`<div class="manager-row"><span>${f.label} · 추가 항목</span><button type="button" class="danger" data-remove-custom="${f.key}">삭제</button></div>`));box.querySelectorAll('[data-remove-fixed]').forEach(b=>b.onclick=()=>{document.querySelector(`[data-field-id="${b.dataset.removeFixed}"]`)?.remove();manager()});box.querySelectorAll('[data-remove-custom]').forEach(b=>b.onclick=()=>{custom=custom.filter(f=>f.key!==b.dataset.removeCustom);renderCustom();manager()})}
function splitPanels(){const panels=[...document.querySelectorAll('.grid > .panel')];const groups=[[['rackSpec'],'랙 구성'],[['buffer'],'버퍼'],[['tote'],'토트'],[['acr','acrLift','acrLoad'],'ACR'],[['amr','amrLoad','dispatch','charge','station','times'],'AMR']];groups.forEach(([ids,title],index)=>{const panel=panels[index<3?0:1],inner=panel?.querySelector('.panel-inner');if(!inner||inner.querySelector(`[data-group="${title}"]`))return;const group=document.createElement('div');group.className='field-group';group.dataset.group=title;group.innerHTML=`<h4>${title}</h4><div class="fields"></div>`;const host=group.querySelector('.fields');ids.forEach(id=>{const field=inner.querySelector(`[data-field-id="${id}"]`);if(field)host.appendChild(field)});inner.appendChild(group)})}
const originalShowApp=showApp;showApp=async u=>{await originalShowApp(u);splitPanels()};
